
management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

info:
  application:
    name: spring-blog
    description: A blog with articles about The Spring Framework.
    author: Dan Vega
    version: '@project.version@'
spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    name: spring-blog
  jpa:
    properties:
      hibernate:
        dialect:org.hibernate.dialect.PostgreSQLDialect
  profiles:
    active: dev